name: Bug Report
description: Create a bug report to help us improve Aurory
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Player Name, Discord ID, email
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: |
        Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the behaviour.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expect!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Other
  - type: dropdown
    id: wallet
    attributes:
      label: Which wallet are you using?
      multiple: true
      options:
        - No wallet
        - Phantom
        - Solflare
        - Sollet
        - Backpack
        - Slope
        - Sollet (extension)
        - Other
  - type: textarea
    id: attachments
    attributes:
      label: Screenshots / Videos capture / Attachments
      placeholder: |
        Add an in-game screenshot / video of the issue which includes the Session and/or Battle ID (located in the lower left corner of the screen).
        If applicable: Add a screenshot of the console (Tap F12 > Click "Console").
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aurory.io/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true